re PR other/47467 (hwint.h:239:3: error: implicit declaration of function 'abs')
	PR bootstrap/47467
	* targext.c: Include target files if IN_RTS is defined.

From-SVN: r169632