re PR c++/47952 ([trans-mem] undefined reference to transaction clone)
        PR 47952
        * trans-mem.c (tm_mangle): Pass in and return an identifier.
        (ipa_tm_create_version): Update to match.  Also mangle the
        DECL_COMDAT_GROUP.

From-SVN: r170768