morello testsuite: Fix up global-constants.c test
This test had the construct:

char * __capability stringval = "abcdef";

which is rejected when compiling for hybrid with:

error: initializer element is not valid for capability type

since the RHS has non-capability type, the LHS has capability type, and
GCC (unlike CHERI LLVM) doesn't allow the __capability type information
to flow from the LHS to the RHS here.

so to fix the test, we drop the __capability annotation from this
variable. We also adjust a dg-warning check that is expected not to fire
on hybrid. Finally, we drop some unnecessary defines and make some other
minor cleanups.

Overall the changes allow the test to pass in all configruations.